server:
  port: 8030
  connection-timeout: 6000
logging:
  level:
    org.springframework: WARN
security:
  sessions: NEVER
info:
  name: ${spring.application.name}
  version: ${project.version}
spring:
  application:
    name: payplatform-develop
  redis:
    host: 10.164.194.123
    port: 10001
    pool:
      max-idle: 100
      min-idle: 10
      max-active: 1000
  rabbitmq:
    addresses: 10.164.197.208:5672,10.164.197.228:5672
    username: admin
    password: admin123
    virtual-host: /
    publisher-confirms: true
    listener:
      simple:
        acknowledge-mode: auto # 确认模式
        concurrency: 1 # 最小消费者数量
    requestedHeartbeat: 60
    exchange: APPMSG_TOPIC_EXCHANGE
    queue:
      cmis_payplatform_queue: APPMSG_OUTPLAT_CMISMSG_QUEUE_46
  http:
    converters:
      preferred-json-mapper: fastjson # json 转换器, 接收数据和请求数据时使用
      preferred-xml-mapper: jackson # xml 转换器, 请求数据时使用
    encoding:
      force: true # 强制用 UTF-8 编码解析请求
    multipart:
      max-file-size: 10MB # 最大文件大小
      max-request-size: 10MB # 最大请求大小
redis:
  single:
    host: 10.164.194.123
    port: 10001
  # cluster:
  #   address: 192.168.1.17:7001,192.168.1.17:7002,192.168.1.17:7003
  #   timeout: 300000
  #   maxRedirections: 6
  pool:
    maxWaitMillis: -1
    maxTotal: 1000
    maxIdle: 100
    minIdle: 10
    testOnBorrow: true
datasources:
  payplatform:
    datasource:
      url: jdbc:oracle:thin:@10.164.194.168:1521/haiercash
      username: haiercashpay
      password: haiercashpay
      driverClassName: oracle.jdbc.OracleDriver
      # 连接池配置
      # type: com.alibaba.druid.pool.DruidDataSource
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      # poolPreparedStatements: true
      # maxPoolPreparedStatementPerConnectionSize: 21
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 ,wall,commonLogging
      filters: stat,wall,commonLogging
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      # connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    druid:
      path: /druid/*
      loginUsername: admin
      loginPassword: admin
    mybatis:
      dialect: org.apache.ibatis.dialect.OracleDialect
      basePackage: com.haiercash.commons.dao,com.haiercash.payplatform.**.dao
      aliasesPackage: com.haiercash.commons.data,com.haiercash.payplatform.**.data
      mapperLocations: classpath*:com/haiercash/commons/mapping/*.xml,classpath*:com/haiercash/payplatform/**/mapping/*.xml
      underscoreToCamelCase: true
eureka:
  client:
    register-with-eureka: true # 是否注册自身到 eureka 服务器
    fetch-registry: true # 是否从 eureka 服务器获取注册信息
    registryFetchIntervalSeconds: 5
    eurekaServiceUrlPollIntervalSeconds: 120
    serviceUrl:
      defaultZone: http://10.164.197.208:1180/eureka/,http://10.164.197.209:1180/eureka/
  instance:
    instanceId: ${spring.application.name}@${spring.cloud.client.ipAddress}:${server.port}(${spring.cloud.client.hostname})
    appname: ${spring.application.name}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    secure-port-enabled: false
zuul:
  ignoredServices: '*'
  set-content-length: true # 返回长度,微服务没有返回长度或请求 GZip 压缩除外
  host:
    socket-timeout-millis: 30000
  routes:
    crmForApp:
      path: /app/appserver/**
      serviceId: APPSERVERNOAUTHNEW
      stripPrefix: false
      sensitive-headers:
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
  route-headers-enabled: false
  eureka:
    enabled: true
common:
  redis:
    host: 10.164.194.123
    port: 10001
    prefix: "PAYPLATFORM:"
app:
  address:
    gateUrl: http://testpm.haiercash.com
  redis:
    prefix: PAYPLATFORM
    expire: 3600 # 过期时间，以秒为单位
  file:
    uploadPath: f:\file\upload # 文件上传路径
    templatePath: f:\file\template # excel模板文件路径
  rest:
    APPCA: http://APPCA
    APPMANAGE: http://APPMANAGE
    APPMSG: http://APPSERVER-MSG
    APPSERVER: http://APPSERVER
    APPSERVERNOAUTH: http://APPSERVERNOAUTH
    APPSERVERNOAUTHNEW: http://APPSERVERNOAUTHNEW
    CMISPROXY: http://CMISPROXY
    CRM: http://CRM-PREPARE
    HCPORTAL: http://HCPORTAL
    CMISFRONTSERVER: http://CMIS-FRONT-SERVER
    GM: http://GM
    UAUTH: http://UAUTH
    ACQUIRER: http://ACQUIRER
    ORDER: http://ORDER
  cmis:
    url: http://10.164.194.105:8098/cmis/HTTP_DEMO_SERVICE/ # cmis 服务地址
  other:
    haierDataImg_url: /testshare01/00/Data/haierData/
    outplatform_url: http://10.164.194.120:9080
    face_DataImg_url: /testshare01/crm/image/
    appServer_page_url: http://testpm.haiercash.com/
    haierData_url: http://taccount.haier.com
    haiercashpay_web_url: https://testpm.haiercash.com/
    haiershunguang_ts_url : http://mobiletest.ehaier.com:58093
    moxie_apikey : 51f5eed2f64f467a9a20f15d2ce26038
  shunguang:
    sg_merch_no: EHAIER
    sg_store_no: SHUNGUANG
    sg_user_id: SAQDGM01
    sg_typCde: 17098a
    sg_shopkeeper: 882f7f5c91fc4ed09a754e28841bc7ad
    sg_consumer: dc04a273474a404bafdad48ddb63cce2
  cashLoan:
    whiteTagIds: 49aa1427f97a432e9c1658a5708bd198,ba2dbc42abf347cfba67580118ad1985,36d86a768c624bc784c8a9e6523e2eb5,2e476949487f4c4a81e9ff3bd788930a # 现金贷标签白名单
