server:
  version: -BETA
  port: 8010
  tomcat:
    min-spare-threads: 20
    max-threads: 500
    max-connections: 500
  connection-timeout: 5000
logging:
  file: AppServer.log
  level:
    org.springframework.security: DEBUG
    com.haiercash: DEBUG
security:
  sessions: NEVER
spring:
  application:
    name: AppServer
  redis:
    host: 10.164.194.142
    port: 6379
  datasource:
    url: jdbc:oracle:thin:@10.164.194.168:1521/haiercash
    #url: jdbc:oracle:thin:@10.164.197.17:1521/app2
    testWhileIdle: true
    validationQuery: SELECT 1
    username: appserver
    password: 123456
    #password: appserver123
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    database: ORACLE
    show-sql: true
    hibernate:
      show-sql: true
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
  data:
      rest.base-path: /api/appserver
  rabbitmq:
    addresses: 10.164.197.54:5672, 10.164.197.55:5672
    username: admin
    password: 123456
    virtual-host: /
    publisher-confirms: true
    listener:
      acknowledge-mode: AUTO  # 消费者开启ack
      concurrency: 1  # Listener并行处理的消息数量，可以通过增加此数量提高消息处理效率
    requestedHeartbeat: 60
    exchange: APPMSG_TOPIC_EXCHANGE_DEV
    queue:
      messagestore_outplat_queue: APPMSG_OUTPLAT_CMISMSG_QUEUE
      messagestore_acq_queue: APPMSG_ACQ_CMISMSG_QUEUE
eureka:
  client:
    register-with-eureka: true #是否注册自身到eureka服务器
    fetch-registry: true #是否从eureka服务器获取注册信息
    registryFetchIntervalSeconds: 5
    eurekaServiceUrlPollIntervalSeconds: 120
    serviceUrl:
      defaultZone: http://10.164.197.208:1180/eureka/,http://10.164.197.209:1180/eureka/
      #defaultZone: http://10.164.197.32:1180/eureka/,http://10.164.197.33:1180/eureka/,http://10.164.197.34:1180/eureka/
  instance:
    instanceId: ${spring.application.name}-${application.version}@${spring.cloud.client.ipAddress}:${server.port}(${spring.cloud.client.hostname})
    appname: ${spring.application.name}-ZHOU # 开发时，在这里加上唯一标识，比如姓名全拼，方便识别
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    secure-port-enabled: false
    prefer-ip-address: true
zuul:
  ignoredServices: '*'
  host:
    socket-timeout-millis: 30000
  routes:
    crmForApp:
      path: /app/crm/**
      serviceId: CRM-BETA
      stripPrefix: false
      sensitive-headers:
    crmForPub:
      path: /pub/crm/**
      serviceId: CRM-BETA
      stripPrefix: false
      sensitive-headers:
    uauthForApp:
      path: /app/uauth/**
      serviceId: UAUTH-BETA
      stripPrefix: false
      sensitive-headers:
    uauthForPub:
      path: /pub/uauth/**
      serviceId: UAUTH-BETA
      stripPrefix: false
      sensitive-headers:
    gmForApp:
      path: /app/gm/**
      serviceId: GM-BETA
      stripPrefix: false
      sensitive-headers:
    gmForPub:
      path: /pub/gm/**
      serviceId: GM-BETA
      stripPrefix: false
      sensitive-headers:
    appmanage:
      path: /appmanage/**
      serviceId: APPMANAGE
      sensitive-headers:
    appmanageForApp:
      path: /app/appmanage/**
      serviceId: APPMANAGE
      stripPrefix: false
      sensitive-headers:
    img:
      url: http://10.164.194.142:4869
    portalForApp:
      path: /app/portal/**
      serviceId: HCPORTAL-BETA
      stripPrefix: false
      sensitive-headers:
    portalForPub:
      path: /pub/portal/**
      serviceId: HCPORTAL-BETA
      stripPrefix: false
      sensitive-headers:
    cmisproxyForApp:
      path: /app/cmisproxy/**
      #serviceId: portal
      serviceId: HCPORTAL-BETA
      stripPrefix: false
      sensitive-headers:
    pub/cmisfront:
      url: http://10.164.194.102:8081/0
    pub/cmiscore:
      url: http://10.164.194.102:8081/9
    pub/sms:
      url: http://testpm.haiercash.com/Outreachplatform/api/msg
    app/face:
      url: http://10.164.194.123:9080/Outreachplatform/api/face
#HCPortal:
HCPORTAL-BETA:
  ribbon:
    listOfServers: http://10.164.197.22:8080
portal:
  ribbon:
    listOfServers: http://10.164.197.22:8080
crm:
  ribbon:
    listOfServers: http://10.164.194.115:8081
uauth:
  ribbon:
    listOfServers: http://10.164.194.118:8083
gm:
  ribbon:
    listOfServers: http://10.164.194.116:8082
appmanage:
  ribbon:
    #listOfServers: http://10.164.194.115:8180
    listOfServers: http://localhost:8180
contract:
  ribbon:
    listOfServers: http://localhost:8092
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
  eureka:
    enabled: true
common:
  redis:
    host: 10.164.194.142
    port: 6379
  sign:
    templatePath: E:\upload\template\
    uploadPath: E:\upload\temp\
    openOfficeServiceIp: 10.164.194.115
    openOfficeServicePort: 8100
    sysFlag: "04"
    channelNo: "05"
    CaServiceUrl: http://10.164.194.119:8080/api
    CaAppId: haier
    CaAppSecret: EPIhG9YQT/OUf1VOcydSUcvOmFk=
    NewCaServiceUrl: http://10.164.194.119:8080/api
    NewCaAppId: haier
    NewCaAppSecret: EPIhG9YQT/OUf1VOcydSUcvOmFk=
    NewtemplatePath: C:\\Users\\Administrator\\Desktop\\PDF\\
    haierSignNo: 62083dcd-1980-47b8-9c71-b3f1cbc15815
    CaFolder: c:/caFile
    CaDocType: DOC014
  address:
    gateUrl: http://HCPORTAL-BETA
    #gateUrl: http://HCPORTAL
    gateIp: http://10.164.194.115:8000
    outplatform: http://10.164.194.123:9080
  sms:
    isEnabled: true
    channelNo: haiercash
    appendID:
    verifyNoTpl: 【海尔消费金融】您的验证码为%s,请勿泄露并在5分钟内输入，如非本人操作，请致电4000187777。
    verifyKeyPrefix: _SMS_VERIFY_
    verifyExpire: 300
    resendSpan: 60
  file:
    imageFolder: c:/attachFile
    imageMaxSize: 5242880
    imageSysFlag: "00"
    imageBizFlag: LcAppl
    imageBankCardFlag: LmAcctChg
    imageCrmFlag: crm
    imageImageFlag: image
    imageCrmFolder: c:/attachCrmFile
    imageCache: imageCache
  other:
    faceThreshold: 40
    faceThreshold2: 0
    faceCountLimit: 3
    bigDataFaceCountLimit: 2
    faceAttachType: DOC065
    isXingeEnabled: false
    isMsgSendEnabled: true
    redisKeyMsgSend: __APP_SERVER_MSG_SEND_STACK_111
    isCAEnabled: false
    redisKeyCA: __APP_SERVER_CA_STACK_111
    redisKeyCASigning: __APP_SERVER_CA_SIGNING_1
    redisKeyXingePush: _APP_SERVER_XINGEPUSH_STACK
    redisKeyImportOrder: _APP_SERVER_IMPORT_ORDER
    redisKeyXcdloanToSend: _APP_SERVER_XCD_LOAN_TO_SEND
    redisKeyCAResigning: _APP_SERVER_CA_RESIGNING_21
    ACCESSID_IOS_MERCH: 2200203660
    ACCESSID_IOS_USER: 2200202606
    SECRETKEY_IOS_MERCH: 623b85693fc49d08131698153dcefe6a
    SECRETKEY_IOS_USER: 579728766aac76ccefec1ea7563ff6f3
    ACCESSID_ANDROID_MERCH: 2100196084
    ACCESSID_ANDROID_USER: 2100196085
    SECRETKEY_ANDROID_MERCH: 88b83a09997b26f1ce38433a5894b08b
    SECRETKEY_ANDROID_USER: cb13b89ca36f73c268c7e0c4192f3ba4
    MAX_CREDIT: 200000
    isImportOrderEnabled: false      #支付平台的定时任务是否启动
    importOrderExpiredTime:  100    #支付平台订单有效小时数
    smsConfirm: true
    domain: http://testpm.haiercash.com
    isEdMsgSendEnabled: true
    redisKeyEdMsgSend: __APP_SERVER_MSG_ED_SEND_STACK_111
  xcd:
    typCde: 16139a
    faceThreshold: 40
  meifenqi:
    typCde: 16076a
  qrdz:
    typCde: 16077a
    back_url: http://139.196.45.193:20011
  app:
    isEncode: true
    checkAuth: false
  face:
    face_api_key: D9svZuIdQ6uCqqBk4UMB2xiTLgKtVFLS
    face_api_secret: PYDHtPUnDzBcXvQsyDSyfFIBjuWI5w8K
    face_gettoken_url: https://api.megvii.com/faceid/lite/get_token
    face_getresult_url: https://api.megvii.com/faceid/lite/get_result
    face_DataImg_url: /testshare01/crm/image/
EUREKASERVER:
  APPCA: http://APPCA
  APPMANAGE: http://APPMANAGE
  APPMSG: http://APPSERVER-MSG
  CMISPROXY: http://CMISPROXY
  CMISFRONTSERVER: http://CMIS-FRONT-SERVER
  CRM: http://CRM${server.version}
  #CRM: http://CRM
  HCPORTAL: http://HCPORTAL-BETA
  GM: http://GM${server.version}
  UAUTH: http://UAUTH${server.version}
  #UAUTH: http://UAUTH
  ACQUIRER: http://ACQUIRER
  ORDER: http://ORDER
  APPSERVER: http://APPSERVER
  APPSERVERNOAUTH: http://APPSERVERNOAUTH

