# 封测环境
server:
  port: 8030
  connection-timeout: 6000
logging:
  level:
    org.springframework: warn
security:
  sessions: never
info:
  name: payplatform
  description: 支付平台-封测环境
spring:
  application:
    name: ${info.name}
    description: ${info.description}
    version: ${info.version}
  http:
    converters:
      preferred-json-mapper: fastjson # json 转换器, 接收数据和请求数据时使用
      preferred-xml-mapper: jackson # xml 转换器, 请求数据时使用
    encoding:
      force: true # 强制用 UTF-8 编码解析请求
    multipart:
      max-file-size: 10MB # 最大文件大小
      max-request-size: 10MB # 最大请求大小
  rest:
    connect-timeout: 3000
    read-timeout: 60000
    route-headers-enabled: false
    ignore-headers:
  redis:
    cluster:
      nodes: 10.164.204.22:10001,10.164.204.22:10002,10.164.204.22:10003,10.164.204.22:10004,10.164.204.22:10005,10.164.204.22:10006
      max-redirects: 3
    timeout: 10000
    pool:
      max-idle: 200
      min-idle: 100
      max-active: 1000
    global-key-prefix: PAYPLATFORM # 全局前缀, 自动用 ':' 分割
    default-value-expire: 3600 # 默认字符串过期时间, 单位:秒
  rabbitmq:
    addresses: 10.164.197.208:5672,10.164.197.228:5672
    username: admin
    password: admin123
    virtual-host: /
    publisher-confirms: true
    requested-heartbeat: 60
    listener:
      simple:
        acknowledge-mode: auto # 确认模式
        concurrency: 1 # 最小消费者数量
  datasource:
    url: jdbc:oracle:thin:@10.164.197.49:1521:ibank
    username: haiercashpay
    password: haiercashpay
    driver-class-name: oracle.jdbc.OracleDriver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall,commonLogging
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
  mybatis:
    dialect: org.apache.ibatis.dialect.OracleDialect
    base-package: com.haiercash.**.dao
    aliases-package: com.haiercash.**.data
    mapper-locations: classpath:/com/haiercash/**/mapping/*.xml
    underscore-to-camel-case: true
  mail:
    forward: false
    host: smtp.ym.163.com
    port: 25
    username: email@bestvike.com
    password: 123456
    properties:
      mail.smtp.ssl.enable: false
      mail.smtp.starttls.enable: true
    async: false
    rabbit:
      exchange:
      routing-key:
      queue:
    bug-report:
      enabled: true
      level: error
      queue-size: 10
      send-interval-seconds: 120
      subject: 【海尔消费金融】错误报告
      to: lijianyu@bestvike.com,xuchonglei@bestvike.com,yuanli@bestvike.com,zhaoxianlu@bestvike.com,sunyinhang@bestvike.com
      cc: zhuxiaoxue@bestvike.com,chijiepeng@bestvike.com
      bcc:
eureka:
  client:
    register-with-eureka: true # 是否注册自身到 eureka 服务器
    fetch-registry: true # 是否从 eureka 服务器获取注册信息
    registry-fetch-interval-seconds: 5
    eureka-service-url-poll-interval-seconds: 120
    service-url:
      defaultZone: http://10.164.197.32:1180/eureka/,http://10.164.197.33:1180/eureka/,http://10.164.197.34:1180/eureka/
  instance:
    instanceId: ${spring.application.name}@${spring.cloud.client.ipAddress}:${server.port}(${spring.cloud.client.hostname})
    appname: ${spring.application.name}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    secure-port-enabled: false
zuul:
  ignored-services: '*'
  set-content-length: true # 返回长度,微服务没有返回长度或请求 GZip 压缩除外
  host:
    socket-timeout-millis: 30000
  routes:
    crmForApp:
      path: /app/appserver/**
      service-id: APPSERVERNOAUTHNEW
      strip-prefix: false
      sensitive-headers:
app:
  common:
    gate-url: https://testpm.haiercash.com:9002 # 程序前缀
  rest:
    ACQUIRER: http://ACQUIRER
    APPCA: http://APPCA
    APPMANAGE: http://APPMANAGE
    APPMSG: http://APPSERVER-MSG
    APPSERVER: http://APPSERVER-NEW
    APPSERVERNOAUTHNEW: http://APPSERVERNOAUTHNEW
    CMISFRONTSERVER: http://CMIS-FRONT-SERVER
    CMISINTERFACESERVER: http://CMIS-INTERFACE-SERVER
    CMISPROXY: http://CMISPROXY
    CRM: http://CRM-PREPARE
    GM: http://GM
    HCPORTAL: http://HCPORTAL
    ORDER: http://ORDER
    OUTREACHPLATFORM: http://OUTREACHPLATFORM
    UAUTH: http://UAUTH
  storage:
    ocr-path: /testshare01/00/Data/haierData
    face-path: /testshare01/crm/image
  cmis:
    url: # cmis 服务地址
    rabbit:
      exchange: APPMSG_TOPIC_EXCHANGE
      routing-key:
      queue: APPMSG_OUTPLAT_CMISMSG_QUEUE_46
  outreach:
    appid: 300000762
    channel-no: HCP
  haier:
    account-url: https://taccount.haier.com
  moxie:
    api-key: 51f5eed2f64f467a9a20f15d2ce26038
  shunguang:
    merch-no: EHAIER
    store-no: SHUNGUANG
    user-id: SAQDGM01
    typ-cde: 17033a
    shop-keeper: 882f7f5c91fc4ed09a754e28841bc7ad
    consumer: dc04a273474a404bafdad48ddb63cce2
    ts-url: http://mobiletest.ehaier.com:58093
  cashloan:
    white-tag-ids: cf92ff4d567a4503b61a1eb6f205e602,0b56f7f13a1d4a8dbaf88de93a1defd5,8448c908e2ce43ee98ba35a4f07de325,d6b98a9329f04b27af52add933acd804,5af7f6657df64f648b45686fc26b7c40
    iservice-tag-id: 5af7f6657df64f648b45686fc26b7c40
    days: 30
  weixin:
    appid: wx765f132310ed7371
    secret: c400d6495e25f2401b5a7209585fc56c
  alipay:
    url: https://openapi.alipay.com/gateway.do
    app-id: 2017123001383623
    app-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCL2tRXSFD/5WeLvkApJW/yjKsFhPZLcDfUcShYyts0eYri/is5/0MlMeq6RbdhKkuthyUvd6tA07TB6/yRcsNw3lQlpItw6gzzpkx46khJ/SX78VIEbe2d1/zYMzF/Km91L3Jb297fqzIziIsMnFkemrvbGByRJjLdynFxrqXl0eyP1o9VPaBcPXUukOBekAwMUC/8s0PZnNZmneZlilNmxEl/dRuXxJhjfxB7vsrPvB9VcINg3oT068B+U1MOVdOEYnZX3dRBhqRUMMwKdzzePMX6eMboFWUrM69V51LcmU3rinuGecHapxnvUmFpb+se4dZaJiJXzRLVdgNipxtjAgMBAAECggEAPog2v1wHU5PIK5SCbaNena3F3i7oTSy82dFKwADb6Geb8QjCXSlEZYIfOPBpIRnfQpSVzNaODOtb/AU/Je2Rc4sFRtt+uZr89Yha0wm2DtcQv8jT6kUYpKXpWOXy8LARq+zuDiKOUaXjSWV4/sd9lZCMBFeQllnlDoQxGyqC5PHBlWPLbHr4LIvC5k22fF8H7AqhZoZHEeSZPUCGGZE6ZhFP8+XinZTYQIZ+e0Hlu10gV3Y+An2HHJn8iOAUbJjwPn0kt+/N8lqGO4WhTuT+1fO3peCfIpQLW3tGAAVz7q4O+ipYM+j7CFuU629PCTxFlOTA4PMj8BE+gtEeZgB2aQKBgQDGZbAhVQwVehUbfU6XrEi1wCjmMZ6w04dBmwfAP9/bcV6jKl0wjl86jzTcbTDcnTcL3Mqq400+ufm6fzUmdNOHPWy9k7FGRH2EYWMIjXJDtoUH16YPo7h9PpAoRlYD9CwlTtuzM8B3Nfsv9GYhUV9qALV1F3JfhfsC7YW3OzA4ZQKBgQC0ddjPKd76i+Df7xbSm2TNVndaRv+7p6OUe2ghvkTSa6MDbLWGfIlV2YrnhS5xVfSddMOJR96Tn8LzdZXnFnGYdDybOCuPSet1vROhHXn9XdNaWn0OaPLxoDVDL5UMOzP3DIxgLyOjnpymNClAe31cP8vl7IksKQHe8nyTENI0JwKBgEhVTs/4R/2UkxmAqCTYZXIOa1ryAF+L36ZltX+8Sguh29U1XuCTJ9kb2TP8g3ILx8QFbca8NK+H8qqyMlihA3YtSPYdYOazleer8gVuPJi/dOUVFLBjCqJvKvPkIPw0C9xWUfeWCLft8HTdcFb5agYl2AKm18ZH/OpmWvghFkWZAoGAH5bBbQIXViRGKOzhQdyRuJ/6JINpIKAnskYn5EA6K9tLnb3ZyMDkCXMbLYvSpWQ2fZmC4PUDsTO2HIfoxZrYJ6exNDqQ5XQ7E1EVro5KXF+gL6DHY05buJAiwrABlzKF1ikMKYoW4v1Qzocy8Wasewlv17+gA2rqOOyZgeTf5uECgYEAj/X7A5HZqQZEa6qPa9G7LA/zr8v/y0wzS1bN+hVgZ6jEDIHwUmivOp3X98k7P5lIuqhaC9LOZfn9RkwR/57ZvnY+KldMPYYE8c9eP1e+3iqkgFgU50DuoGamJfaAEbmBwdCZryqCNScnVuWnG6bvfpqBUWxdFL/r1IQcz4Mf+30=
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAj0O5+7wAtqv4OImWHlDX7+rRc8H4peIcykwip2+zNatRNYe0qHj/Jl4CKshSwwmu5tvFTxrF6NJF8Yicz1AFnbsy7js90r5YUrwQlplOMY2YCZbCx18dp/0vGeRl9Mn0QrI7iCUxvcdqOq16J3ZbFh0TTnY9zS7YvpcBqz9RTFgvAXyd236J83MSaFo7+WmPlbqjwDWu2IiEPnbAe9uy6pTCFVjsSP8J7ZeQese2dwKy9RKah9Ll7dpHHbO78qLgYcJvalkisDA55PNHTMV206mcYAQbYpY9kgsH+lQ7DmuXp3AwhaM1A/yuU+ImOYMO88XPTVNJubUgdWZYvHDsMwIDAQAB
    fuwu-min-score: 600
    wap-pay-return-url: /alipay/#!/loan/orderSucc.html
    wap-pay-notify-url: http://testpm.haiercash.com/api/foreign/bankfront/callBack/aliDeductCallBack
    wap-pay-subject: 现金贷还款
