# 生产环境
server:
  port: 8030
  connection-timeout: 6000
logging:
  level:
    org.springframework: warn
security:
  sessions: never
info:
  name: payplatform
  description: 支付平台
spring:
  application:
    name: ${info.name}
    description: ${info.description}
    version: ${info.version}
  http:
    converters:
      preferred-json-mapper: fastjson # json 转换器, 接收数据和请求数据时使用
      preferred-xml-mapper: jackson # xml 转换器, 请求数据时使用
    encoding:
      force: true # 强制用 UTF-8 编码解析请求
    multipart:
      max-file-size: 10MB # 最大文件大小
      max-request-size: 10MB # 最大请求大小
  rest:
    connect-timeout: 3000
    read-timeout: 60000
    route-headers-enabled: false
    ignore-headers:
  redis:
    cluster:
      nodes: 10.164.207.69:10001,10.164.207.69:10002,10.164.207.70:10001,10.164.207.70:10002,10.164.207.71:10001,10.164.207.71:10002
      max-redirects: 3
    timeout: 10000
    pool:
      max-idle: 200
      min-idle: 100
      max-active: 1000
    global-key-prefix: PAYPLATFORM # 全局前缀, 自动用 ':' 分割
    default-value-expire: 3600 # 默认字符串过期时间, 单位:秒
  rabbitmq:
    addresses: 10.164.196.209:5672,10.164.196.210:5672
    username: admin
    password: admin123
    virtual-host: /
    publisher-confirms: true
    requested-heartbeat: 60
    listener:
      simple:
        acknowledge-mode: auto # 确认模式
        concurrency: 1 # 最小消费者数量
  datasource:
    url: jdbc:oracle:thin:@10.164.193.69:1521:ibank
    username: haiercashpay
    password: haiercashpay
    driver-class-name: oracle.jdbc.OracleDriver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall,commonLogging
      web-stat-filter:
        enabled: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
  mybatis:
    dialect: org.apache.ibatis.dialect.OracleDialect
    base-package: com.haiercash.**.dao
    aliases-package: com.haiercash.**.data
    mapper-locations: classpath:/com/haiercash/**/mapping/*.xml
    underscore-to-camel-case: true
  mail:
    forward: false
#    host:
    port:
    username:
    password:
    properties:
      mail.smtp.ssl.enable: false
      mail.smtp.starttls.enable: true
    async: false
    rabbit:
      exchange:
      routing-key:
      queue:
    bug-report:
      enabled: false
      level: warn
      queue-size: 10
      send-interval-seconds: 120
      subject: 【海尔消费金融】错误报告
      to:
      cc:
      bcc:
eureka:
  client:
    register-with-eureka: true # 是否注册自身到 eureka 服务器
    fetch-registry: true # 是否从 eureka 服务器获取注册信息
    registry-fetch-interval-seconds: 5
    eureka-service-url-poll-interval-seconds: 120
    service-url:
      defaultZone: http://10.164.196.180:1180/eureka/,http://10.164.196.182:1180/eureka/,http://10.164.196.185:1180/eureka/
  instance:
    instanceId: ${spring.application.name}@${spring.cloud.client.ipAddress}:${server.port}(${spring.cloud.client.hostname})
    appname: ${spring.application.name}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    secure-port-enabled: false
zuul:
  ignored-services: '*'
  set-content-length: true # 返回长度,微服务没有返回长度或请求 GZip 压缩除外
  host:
    socket-timeout-millis: 30000
  routes:
    crmForApp:
      path: /app/appserver/**
      service-id: APPSERVERNOAUTHNEW
      strip-prefix: false
      sensitive-headers:
app:
  common:
    gate-url: https://www.haiercash.com:15006 # 程序前缀
  rest:
    ACQUIRER: http://ACQUIRER
    APPCA: http://APPCA
    APPMANAGE: http://APPMANAGE
    APPMSG: http://APPSERVER-MSG
    APPSERVER: http://APPSERVER-NEW
    APPSERVERNOAUTHNEW: http://APPSERVERNOAUTHNEW
    CMISFRONTSERVER: http://CMIS-FRONT-SERVER
    CMISINTERFACESERVER: http://CMIS-INTERFACE-SERVER
    CMISPROXY: http://CMISPROXY
    CRM: http://CRM
    GM: http://GM
    HCPORTAL: http://HCPORTAL
    ORDER: http://ORDER
    OUTREACHPLATFORM: http://OUTREACH
    UAUTH: http://UAUTH
  storage:
    ocr-path: /storage2018/00/Data/haierData
    face-path: /storage2018/crm/image
  cmis:
    url: # cmis 服务地址
    rabbit:
      exchange: APPMSG_TOPIC_EXCHANGE
      routing-key:
      queue: APPMSG_OUTPLAT_CMISMSG_QUEUE_46
  outreach:
    appid: 300001074
    channel-no: HCP
  haier:
    account-url: http://account.haier.com
  moxie:
    api-key:
  shunguang:
    merch-no: EHAIER
    store-no: SHUNGUANG
    user-id: EH3623
    typ-cde: 17033a
    shop-keeper: 882f7f5c91fc4ed09a754e28841bc7ad
    consumer: dc04a273474a404bafdad48ddb63cce2
    ts-url: http://pay.ehaier.com
  cashloan:
    white-tag-ids: cf92ff4d567a4503b61a1eb6f205e602,0b56f7f13a1d4a8dbaf88de93a1defd5,8448c908e2ce43ee98ba35a4f07de325,d6b98a9329f04b27af52add933acd804,5af7f6657df64f648b45686fc26b7c40
    iservice-tag-id: 5af7f6657df64f648b45686fc26b7c40
    days: 0
  weixin:
    appid: wx046cbd2b50704fbc
    secret: 3cff4ee0fd7594270200a8ad55cf1984
  alipay:
    url: https://openapi.alipay.com/gateway.do
    app-id:
    app-private-key:
    alipay-public-key:
    fuwu-min-score: 600
    wap-pay-return-url: /alipay/#!/loan/orderSucc.html
    wap-pay-notify-url: http://xx
    wap-pay-subject: 现金贷还款
    wap-pay-timeout: 1
